# Generated by Django 2.2.2 on 2019-06-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cam_drum_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_slug',
            field=models.SlugField(default=''),
        ),
    ]
