# Generated by Django 2.2.2 on 2019-06-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cam_drum_site', '0002_topic_topic_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_title',
            new_name='title',
        ),
    ]
